### ISSUE TITLE
LFS support

### ISSUE THREAD

**Issue by sjamisorc** [christianspecht/scm-backup-docs#1]
Does scm-backup have support for repositories with LFS files?

**Comment by christianspecht** [comment]
You're talking about [Git LFS](https://git-lfs.github.com/), right? I'm not sure.

I never used it, but as far as I understand the "Getting started" section, you have to set up your local Git client once, and then it works.
⇒ Since SCM Backup uses your local Git client, I guess it should work when you *did* set it up once.

On the other hand - the point of Git LFS seems to be that large files are **not** automatically downloaded when cloning.
But the point of SCM Backup is that it makes a backup by cloning the repo, and expecting that clone to contain **everything**.

I guess I have to try it out ⇒ I just created [a new issue in the main repo](https://github.com/christianspecht/scm-backup/issues/21) for it.
